version: '2'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${DB_EXTERNAL_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "$APP_EXTERNAL_PORT:$APP_INTERNAL_PORT"
    volumes:
      - ./src:/src
    restart: unless-stopped

  db:
    image: postgres:13.1-alpine
    env_file:
      - .env
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
